//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI.AccessControl
{


    public partial class EditStateCombinationControl
    {

        /// <summary>
        /// CurrentObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;

        /// <summary>
        /// StateDefinitionDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl StateDefinitionDataSource;

        /// <summary>
        /// StateDefinitionContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl StateDefinitionContainer;

        /// <summary>
        /// StateDefinitionField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocReferenceValue StateDefinitionField;

        /// <summary>
        /// DeleteStateDefinitionButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton DeleteStateDefinitionButton;

        /// <summary>
        /// RequiredStateCombinationValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator RequiredStateCombinationValidator;
    }
}
