//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI.AccessControl
{


    public partial class SecurableClassDefinitionListForm
    {

        /// <summary>
        /// ErrorMessageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.SecurityManager.Clients.Web.UI.ErrorMessageControl ErrorMessageControl;

        /// <summary>
        /// CurrentObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;

        /// <summary>
        /// SecurableClassDefinitionTree control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.SecurityManager.Clients.Web.Classes.SecurableClassDefinitionTreeView SecurableClassDefinitionTree;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Remotion.SecurityManager.Clients.Web.UI.SecurityManagerMasterPage Master
        {
            get
            {
                return ((Remotion.SecurityManager.Clients.Web.UI.SecurityManagerMasterPage)(base.Master));
            }
        }
    }
}
