//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.Web.Development.WebTesting.TestSite.Shared.Controls
{


    public partial class BocTextValueUserControl
    {

        /// <summary>
        /// FormGridManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.FormGridManager FormGridManager;

        /// <summary>
        /// CurrentObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;

        /// <summary>
        /// CurrentObjectValidationResultDispatchingValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.Validation.BindableObjectDataSourceControlValidationResultDispatchingValidator CurrentObjectValidationResultDispatchingValidator;

        /// <summary>
        /// FormGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable FormGrid;

        /// <summary>
        /// LastNameField_Normal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_Normal;

        /// <summary>
        /// LastNameField_ReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_ReadOnly;

        /// <summary>
        /// LastNameField_Disabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_Disabled;

        /// <summary>
        /// LastNameField_NoAutoPostBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_NoAutoPostBack;

        /// <summary>
        /// LastNameField_PasswordRenderMasked control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_PasswordRenderMasked;

        /// <summary>
        /// LastNameField_PasswordNoRender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_PasswordNoRender;

        /// <summary>
        /// CVString_Normal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue CVString_Normal;

        /// <summary>
        /// CVString_ReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue CVString_ReadOnly;

        /// <summary>
        /// CVString_Disabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue CVString_Disabled;

        /// <summary>
        /// CVString_NoAutoPostBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue CVString_NoAutoPostBack;

        /// <summary>
        /// LastNameField_Normal_Required control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_Normal_Required;

        /// <summary>
        /// UnboundText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue UnboundText;
    }
}
