//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.Web.Development.WebTesting.TestSite.Shared.Controls {
    
    
    public partial class BocTreeViewUserControlTestOutput {
        
        /// <summary>
        /// NormalSelectedNodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NormalSelectedNodeLabel;
        
        /// <summary>
        /// NoTopLevelExpanderSelectedNodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NoTopLevelExpanderSelectedNodeLabel;
        
        /// <summary>
        /// NoLookAheadEvaluationSelectedNodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NoLookAheadEvaluationSelectedNodeLabel;
        
        /// <summary>
        /// NoPropertyIdentifierSelectedNodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NoPropertyIdentifierSelectedNodeLabel;
        
        /// <summary>
        /// ActionPerformedSenderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ActionPerformedSenderLabel;
        
        /// <summary>
        /// ActionPerformedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ActionPerformedLabel;
        
        /// <summary>
        /// ActionPerformedParameterLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ActionPerformedParameterLabel;
    }
}
