// This file is part of the re-motion Core Framework (www.re-motion.org)
// Copyright (c) rubicon IT GmbH, www.rubicon.eu
//
// The re-motion Core Framework is free software; you can redistribute it
// and/or modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2.1 of the
// License, or (at your option) any later version.
//
// re-motion is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with re-motion; if not, see http://www.gnu.org/licenses.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Remotion.Linq.Parsing.ExpressionVisitors.Transformation;

namespace Remotion.Data.DomainObjects.Queries;

/// <summary>
/// Transforms <see cref="MemoryExtensions"/>.<see cref="MemoryExtensions.Contains"/> calls generated by the C# 14 compiler back to their
/// <see cref="Enumerable"/>.<see cref="M:System.Linq.Enumerable.Contains``1(System.Collections.Generic.IEnumerable{``0},``0)"/> equivalent.
/// </summary>
public class SpanContainsExpressionTransformer : IExpressionTransformer<MethodCallExpression>
{
  private static readonly MethodInfo s_memoryExtensionContainsMethod;
  private static readonly MethodInfo s_memoryExtensionContainsMethodWithEqualityComparer;

  private static readonly MethodInfo s_enumerableContainsMethod;
  private static readonly MethodInfo s_enumerableContainsMethodWithEqualityComparer;

  static SpanContainsExpressionTransformer ()
  {
    s_memoryExtensionContainsMethod = FindContainsMethod(typeof(MemoryExtensions), typeof(ReadOnlySpan<>), false);
    s_memoryExtensionContainsMethodWithEqualityComparer = FindContainsMethod(typeof(MemoryExtensions), typeof(ReadOnlySpan<>), true);

    s_enumerableContainsMethod = FindContainsMethod(typeof(Enumerable), typeof(IEnumerable<>), false);
    s_enumerableContainsMethodWithEqualityComparer = FindContainsMethod(typeof(Enumerable), typeof(IEnumerable<>), true);

    static MethodInfo FindContainsMethod (Type type, Type collectionType, bool withEqualityComparer)
    {
      return type.GetMethods()
          .Single(e =>
              IsRelevantMethod(e, collectionType)
              && e.GetParameters().Length == (withEqualityComparer ? 3 : 2));
    }

    // We apply a very specific filter to retrieve:
    //  - XXX.Contains<T>(ReadOnlySpan<T>, T)
    //  - XXX.Contains<T>(ReadOnlySpan<T>, T, IEqualityComparer<T>)
    // We need to handle the equality comparer overload even if re-linq does not
    // support it because the C# compiler will use it with a `null` value.
    static bool IsRelevantMethod (MethodInfo method, Type collectionType)
    {
      if (method.Name != "Contains")
        return false;

      if (!method.IsGenericMethod)
        return false;

      var genericArguments = method.GetGenericArguments();
      if (genericArguments.Length != 1)
        return false;

      var itemType = genericArguments[0];
      var parameters = method.GetParameters();
      if (parameters.Length is < 1 or > 3)
        return false;

      if (parameters[0].ParameterType != collectionType.MakeGenericType(itemType))
        return false;
      if (parameters[1].ParameterType != itemType)
        return false;
      if (parameters.Length > 2 && parameters[2].ParameterType != typeof(IEqualityComparer<>).MakeGenericType(itemType))
        return false;

      return true;
    }
  }

  private static bool IsEnumerableContainsMethod (MethodInfo methodInfo)
  {
    return methodInfo == s_memoryExtensionContainsMethod
           || methodInfo == s_memoryExtensionContainsMethodWithEqualityComparer;
  }

  public SpanContainsExpressionTransformer ()
  {
  }

  public ExpressionType[] SupportedExpressionTypes => [ExpressionType.Call];

  public Expression Transform (MethodCallExpression expression)
  {
    ArgumentNullException.ThrowIfNull(expression);

    // Pre-filter for the relevant MemoryExtensions.Contains overloads
    if (expression.Method.DeclaringType != typeof(MemoryExtensions)
        || expression.Method.Name != "Contains"
        || !expression.Method.IsGenericMethod
        || !IsEnumerableContainsMethod(expression.Method.GetGenericMethodDefinition()))
    {
      return expression;
    }

    var itemType = expression.Method.GetGenericArguments()[0];
    var readOnlySpanType = typeof(ReadOnlySpan<>).MakeGenericType(itemType);

    // We need to check for and remove the implicit span cast that gets generated.
    // User code might also reach this point so we don't YoloCast(tm)
    var collectionArgument = expression.Arguments[0];
    if (collectionArgument is MethodCallExpression { Method.Name: "op_Implicit" } implicitConversion
        && implicitConversion.Method.DeclaringType == readOnlySpanType)
    {
      // Contains has two relevant overloads, one with and one without equality comparer.
      // While re-linq does not support the equality comparer overload, the C# compiler
      // rewrites the overload to the equality comparer one and passes a null value.
      // This break any Contains usage.
      // As such, we rewrite null equality comparer invocations to use the overload
      // without an equality comparer.
      if (expression.Arguments is [_, _, not ConstantExpression { Value: null }])
      {
        return Expression.Call(
            s_enumerableContainsMethodWithEqualityComparer.MakeGenericMethod(itemType),
            implicitConversion.Arguments[0],
            expression.Arguments[1],
            expression.Arguments[2]);
      }

      return Expression.Call(
          s_enumerableContainsMethod.MakeGenericMethod(itemType),
          implicitConversion.Arguments[0],
          expression.Arguments[1]);
    }
    else
    {
      return expression;
    }
  }
}
