//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.UnitTests.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumWithResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumWithResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remotion.ObjectBinding.UnitTests.Globalization.EnumWithResources", typeof(EnumWithResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1.
        /// </summary>
        internal static string Remotion_ObjectBinding_UnitTests_Core_TestDomain_EnumWithResources_Value1 {
            get {
                return ResourceManager.GetString("Remotion.ObjectBinding.UnitTests.TestDomain.EnumWithResources.Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2.
        /// </summary>
        internal static string Remotion_ObjectBinding_UnitTests_Core_TestDomain_EnumWithResources_Value2 {
            get {
                return ResourceManager.GetString("Remotion.ObjectBinding.UnitTests.TestDomain.EnumWithResources.Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 3.
        /// </summary>
        internal static string Remotion_ObjectBinding_UnitTests_Core_TestDomain_EnumWithResources_Value3 {
            get {
                return ResourceManager.GetString("Remotion.ObjectBinding.UnitTests.TestDomain.EnumWithResources.Value3", resourceCulture);
            }
        }
    }
}
