<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>Test</ProjectType>
  </PropertyGroup>
  <Import Project="..\..\..\Build\Shared.build.props" />
  <PropertyGroup>
    <AssemblyTitle>Remotion BusinessObjectControls Library Integration Tests</AssemblyTitle>
    <AssemblyName>Remotion.ObjectBinding.Web.IntegrationTests.New</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Logging.Log4Net\Core.Logging.Log4Net.csproj" />
    <ProjectReference Include="..\..\Web\Development.WebTesting.New\Web.Development.WebTesting.New.csproj" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net10.0'))">
    <ProjectReference Include="..\Web.Development.WebTesting.TestSite\ObjectBinding.Web.Development.WebTesting.TestSite.csproj" ReferenceOutputAssembly="false" ExcludeAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="App.config" />
    <Content Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright.NUnit" />
  </ItemGroup>
  <Import Project="..\..\..\Build\Shared.build.targets" />
</Project>