//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.Web.Test.Shared.Validation {
    
    
    public partial class TestUserControl {
        
        /// <summary>
        /// FormGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable FormGrid;
        
        /// <summary>
        /// LastNameField_UserControlBinding control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField_UserControlBinding;
        
        /// <summary>
        /// FirstNameField_UserControlBinding control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue FirstNameField_UserControlBinding;
        
        /// <summary>
        /// ParterLastNameField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue ParterLastNameField;
        
        /// <summary>
        /// ReferenceField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocReferenceValue ReferenceField;
        
        /// <summary>
        /// DataSourceValidationResultDispatchingValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.Validation.BindableObjectDataSourceControlValidationResultDispatchingValidator DataSourceValidationResultDispatchingValidator;
        
        /// <summary>
        /// FormGridManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.FormGridManager FormGridManager;
        
        /// <summary>
        /// CurrentObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
        
        /// <summary>
        /// PartnerDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BusinessObjectReferenceDataSourceControl PartnerDataSource;
    }
}
