<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>Library</ProjectType>
    <UseWebForms>true</UseWebForms>
  </PropertyGroup>
  <Import Project="..\..\..\Build\Shared.build.props" />
  <PropertyGroup>
    <AssemblyTitle>re-motion Web Testing Framework</AssemblyTitle>
    <Description>Provides a basic infrastructure for performing web tests based on Selenium.</Description>
    <AssemblyName>Remotion.Web.Development.WebTesting.New</AssemblyName>
    <RootNamespace>Remotion.Web.Development.WebTesting</RootNamespace>
    <SignAssembly>False</SignAssembly>
    <NoWarn>$(NoWarn);CS1574</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts.DiagnosticMetadata\Web.Contracts.DiagnosticMetadata.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Remotion.ThirdPartyDependency.LiberationSans" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.Maui.Graphics.Skia" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\SharedSource\Core\Utilities\ArgumentUtility.cs" Link="SharedSource\Utilities\ArgumentUtility.cs" />
    <Compile Include="..\..\..\SharedSource\Core\Utilities\Assertion.cs" Link="SharedSource\Utilities\Assertion.cs" />
    <Compile Include="..\..\..\SharedSource\Core\Utilities\NullableTypeUtility.cs" Link="SharedSource\Utilities\NullableTypeUtility.cs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Remotion.Web.Development.WebTesting.UnitTests"/>
  </ItemGroup>
  <Import Project="..\..\..\Build\Shared.build.targets" />
</Project>