//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.Web.Test.Shared {
    
    
    public partial class CompleteBocForm {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Remotion.ObjectBinding.Web.Test.Shared.StandardMode Master {
            get {
                return ((Remotion.ObjectBinding.Web.Test.Shared.StandardMode)(base.Master));
            }
        }
    }
}
