//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.Web.Development.WebTesting.TestSite.Controls {
    
    
    public partial class BocEnumValueUserControlTestOutput {
        
        /// <summary>
        /// DropDownListNormalCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DropDownListNormalCurrentValueLabel;
        
        /// <summary>
        /// DropDownListNoAutoPostBackCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DropDownListNoAutoPostBackCurrentValueLabel;
        
        /// <summary>
        /// ListBoxNormalCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ListBoxNormalCurrentValueLabel;
        
        /// <summary>
        /// ListBoxNoAutoPostBackCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ListBoxNoAutoPostBackCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListNormalCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListNormalCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListNoAutoPostBackCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListNoAutoPostBackCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListMultiColumnCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListMultiColumnCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListFlowCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListFlowCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListOrderedListCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListOrderedListCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListUnorderedListCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListUnorderedListCurrentValueLabel;
        
        /// <summary>
        /// RadioButtonListLabelLeftCurrentValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label RadioButtonListLabelLeftCurrentValueLabel;
    }
}
