//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.UnitTests.BindableObject.IntergrationTests.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TargetClassForGlobalizationViaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TargetClassForGlobalizationViaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remotion.ObjectBinding.UnitTests.BindableObject.IntergrationTests.Globalization.R" +
                            "esources.TargetClassForGlobalizationViaResources", typeof(TargetClassForGlobalizationViaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property1 display name from TargetClassForGlobalizationViaResources.
        /// </summary>
        internal static string property_Property1 {
            get {
                return ResourceManager.GetString("property:Property1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property2 display name from TargetClassForGlobalizationViaResources.
        /// </summary>
        internal static string property_Property2 {
            get {
                return ResourceManager.GetString("property:Property2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default value.
        /// </summary>
        internal static string property_PropertyForMixinOverrideTest {
            get {
                return ResourceManager.GetString("property:PropertyForMixinOverrideTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MixedExplicitProperty display name from TargetClassForGlobalizationViaResources.
        /// </summary>
        internal static string property_Remotion_ObjectBinding_UnitTests_BindableObject_IntergrationTests_Globalization_TestDomain_IMixinAddingResources_MixedExplicitProperty {
            get {
                return ResourceManager.GetString("property:Remotion.ObjectBinding.UnitTests.BindableObject.IntergrationTests.Global" +
                        "ization.TestDomain.IMixinAddingResources.MixedExplicitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MixedProperty1 display name from TargetClassForGlobalizationViaResources.
        /// </summary>
        internal static string property_Remotion_ObjectBinding_UnitTests_BindableObject_IntergrationTests_Globalization_TestDomain_IMixinAddingResources_MixedProperty1 {
            get {
                return ResourceManager.GetString("property:Remotion.ObjectBinding.UnitTests.BindableObject.IntergrationTests.Global" +
                        "ization.TestDomain.IMixinAddingResources.MixedProperty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExplicitImplementedProperty display name from TargetClassForGlobalizationViaResources.
        /// </summary>
        internal static string property_Remotion_ObjectBinding_UnitTests_BindableObject_IntergrationTests_Globalization_TestDomain_ITargetClassForGlobalizationViaResources_ExplicitImplementedProperty {
            get {
                return ResourceManager.GetString("property:Remotion.ObjectBinding.UnitTests.BindableObject.IntergrationTests.Global" +
                        "ization.TestDomain.ITargetClassForGlobalizationViaResources.ExplicitImplementedP" +
                        "roperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicitImplementedProperty display name from TargetClassForGlobalizationViaResources.
        /// </summary>
        internal static string property_Remotion_ObjectBinding_UnitTests_BindableObject_IntergrationTests_Globalization_TestDomain_TargetClassForGlobalizationViaResources_ImplicitImplementedProperty {
            get {
                return ResourceManager.GetString("property:Remotion.ObjectBinding.UnitTests.BindableObject.IntergrationTests.Global" +
                        "ization.TestDomain.TargetClassForGlobalizationViaResources.ImplicitImplementedPr" +
                        "operty", resourceCulture);
            }
        }
    }
}
