//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.SecurityManager.Clients.Web.UI.OrganizationalStructure {
    
    
    /// <summary>
    /// TenantListForm class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class TenantListForm {
        
        /// <summary>
        /// ErrorMessageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.SecurityManager.Clients.Web.UI.ErrorMessageControl ErrorMessageControl;
        
        /// <summary>
        /// TenantListControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.SecurityManager.Clients.Web.UI.OrganizationalStructure.TenantListControl TenantListControl;
    }
}
