//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.Web.Development.WebTesting.TestSite {
    
    
    public partial class WebTreeViewTest {
        
        /// <summary>
        /// MyWebTreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyWebTreeView;
        
        /// <summary>
        /// MyWebTreeView2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyWebTreeView2;
        
        /// <summary>
        /// MyWebTreeView3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyWebTreeView3;

        /// <summary>
        /// MyOrderedWebTreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyOrderedWebTreeView;

        /// <summary>
        /// MyUnorderedWebTreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyUnorderedWebTreeView;

        /// <summary>
        /// MyWebTreeViewWithCategories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyWebTreeViewWithCategories;
        
        /// <summary>
        /// MyWebTreeViewWithoutCategories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyWebTreeViewWithoutCategories;
        
        /// <summary>
        /// MyWebTreeViewWithUmlauts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebTreeView MyWebTreeViewWithUmlauts;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Remotion.Web.Development.WebTesting.TestSite.Layout Master {
            get {
                return ((Remotion.Web.Development.WebTesting.TestSite.Layout)(base.Master));
            }
        }
    }
}
