//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.Web.Test.Shared.UpdatePanelTests
{


    public partial class SutUserControl
    {

        /// <summary>
        /// ScriptManagerProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManagerProxy ScriptManagerProxy;

        /// <summary>
        /// UpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel;

        /// <summary>
        /// PostBackCountInsideUpdatePanelLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PostBackCountInsideUpdatePanelLabel;

        /// <summary>
        /// LastPostBackInsideUpdatePanelLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LastPostBackInsideUpdatePanelLabel;

        /// <summary>
        /// AsyncPostBackInsideUpdatePanelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AsyncPostBackInsideUpdatePanelButton;

        /// <summary>
        /// SyncPostBackInsideUpdatePanelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SyncPostBackInsideUpdatePanelButton;

        /// <summary>
        /// AsyncPostBackInsideUpdatePanelLinkButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton AsyncPostBackInsideUpdatePanelLinkButton;

        /// <summary>
        /// SyncPostBackInsideUpdatePanelLinkButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton SyncPostBackInsideUpdatePanelLinkButton;

        /// <summary>
        /// AsyncCommandInsideUpdatePanelHyperLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink AsyncCommandInsideUpdatePanelHyperLink;

        /// <summary>
        /// SyncCommandInsideUpdatePanelHyperLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink SyncCommandInsideUpdatePanelHyperLink;

        /// <summary>
        /// AsyncPostBackInsideUpdatePanelWebButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton AsyncPostBackInsideUpdatePanelWebButton;

        /// <summary>
        /// SyncPostBackInsideUpdatePanelWebButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton SyncPostBackInsideUpdatePanelWebButton;

        /// <summary>
        /// DropDownMenuInsideUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.DropDownMenu DropDownMenuInsideUpdatePanel;

        /// <summary>
        /// ListMenuInsideUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.ListMenu ListMenuInsideUpdatePanel;

        /// <summary>
        /// PlaceHolderInsideUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder PlaceHolderInsideUpdatePanel;

        /// <summary>
        /// PlaceHolderOutsideUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder PlaceHolderOutsideUpdatePanel;

        /// <summary>
        /// PostBackCountOutsideUpdatePanelLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PostBackCountOutsideUpdatePanelLabel;

        /// <summary>
        /// LastPostBackOutsideUpdatePanelLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LastPostBackOutsideUpdatePanelLabel;

        /// <summary>
        /// AsyncPostBackOutsideUpdatePanelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AsyncPostBackOutsideUpdatePanelButton;

        /// <summary>
        /// SyncPostBackOutsideUpdatePanelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SyncPostBackOutsideUpdatePanelButton;

        /// <summary>
        /// AsyncPostBackOutsideUpdatePanelLinkButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton AsyncPostBackOutsideUpdatePanelLinkButton;

        /// <summary>
        /// SyncPostBackOutsideUpdatePanelLinkButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton SyncPostBackOutsideUpdatePanelLinkButton;

        /// <summary>
        /// AsyncPostBackOutsideUpdatePanelWebButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton AsyncPostBackOutsideUpdatePanelWebButton;

        /// <summary>
        /// SyncPostBackOutsideUpdatePanelWebButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton SyncPostBackOutsideUpdatePanelWebButton;
    }
}
