//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotion.ObjectBinding.Web.Test.Shared.IndividualControlTests {
    
    
    public partial class BocCheckBoxUserControl {
        
        /// <summary>
        /// NonVisualControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl NonVisualControls;
        
        /// <summary>
        /// FormGridManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.FormGridManager FormGridManager;
        
        /// <summary>
        /// CurrentObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
        
        /// <summary>
        /// CurrentObjectValidationResultDispatchingValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.Validation.BindableObjectDataSourceControlValidationResultDispatchingValidator CurrentObjectValidationResultDispatchingValidator;
        
        /// <summary>
        /// FormGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable FormGrid;
        
        /// <summary>
        /// FirstNameField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue FirstNameField;
        
        /// <summary>
        /// LastNameField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField;
        
        /// <summary>
        /// DeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox DeceasedField;
        
        /// <summary>
        /// DeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DeceasedFieldValueLabel;
        
        /// <summary>
        /// ReadOnlyDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox ReadOnlyDeceasedField;
        
        /// <summary>
        /// ReadOnlyDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReadOnlyDeceasedFieldValueLabel;
        
        /// <summary>
        /// UnboundDeceasedFieldLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.SmartLabel UnboundDeceasedFieldLabel;
        
        /// <summary>
        /// UnboundDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox UnboundDeceasedField;
        
        /// <summary>
        /// UnboundDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label UnboundDeceasedFieldValueLabel;
        
        /// <summary>
        /// UnboundReadOnlyDeceasedFieldLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.SmartLabel UnboundReadOnlyDeceasedFieldLabel;
        
        /// <summary>
        /// UnboundReadOnlyDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox UnboundReadOnlyDeceasedField;
        
        /// <summary>
        /// UnboundReadOnlyDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label UnboundReadOnlyDeceasedFieldValueLabel;
        
        /// <summary>
        /// DisabledDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox DisabledDeceasedField;
        
        /// <summary>
        /// DisabledDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DisabledDeceasedFieldValueLabel;
        
        /// <summary>
        /// DisabledReadOnlyDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox DisabledReadOnlyDeceasedField;
        
        /// <summary>
        /// DisabledReadOnlyDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DisabledReadOnlyDeceasedFieldValueLabel;
        
        /// <summary>
        /// DisabledUnboundDeceasedFieldLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.SmartLabel DisabledUnboundDeceasedFieldLabel;
        
        /// <summary>
        /// DisabledUnboundDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox DisabledUnboundDeceasedField;
        
        /// <summary>
        /// DisabledUnboundDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DisabledUnboundDeceasedFieldValueLabel;
        
        /// <summary>
        /// DisabledUnboundReadOnlyDeceasedFieldLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.SmartLabel DisabledUnboundReadOnlyDeceasedFieldLabel;
        
        /// <summary>
        /// DisabledUnboundReadOnlyDeceasedField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.ObjectBinding.Web.UI.Controls.BocCheckBox DisabledUnboundReadOnlyDeceasedField;
        
        /// <summary>
        /// DisabledUnboundReadOnlyDeceasedFieldValueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DisabledUnboundReadOnlyDeceasedFieldValueLabel;
        
        /// <summary>
        /// DeceasedFieldCheckedChangedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DeceasedFieldCheckedChangedLabel;
        
        /// <summary>
        /// UnboundDeceasedFieldCheckedChangedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label UnboundDeceasedFieldCheckedChangedLabel;
        
        /// <summary>
        /// DeceasedTestSetNullButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton DeceasedTestSetNullButton;
        
        /// <summary>
        /// DeceasedTestToggleValueButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton DeceasedTestToggleValueButton;
        
        /// <summary>
        /// ReadOnlyDeceasedTestSetNullButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton ReadOnlyDeceasedTestSetNullButton;
        
        /// <summary>
        /// ReadOnlyDeceasedTestToggleValueButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Remotion.Web.UI.Controls.WebButton ReadOnlyDeceasedTestToggleValueButton;
    }
}
